spring:
  swagger:
    basePackage: com.liutt.persion.rest.controller     
    title: User Info Rest APIS 
    description: spring cloud demo project
    contactName: LIUTT
    contactUrl: https://github.com/liutit
    contactEmail: 842454909@qq.com
    version: 1.0
#开启feign对Hystrix的支持
feign:
  hystrix:
    enabled: true
#hystrix超时设置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutinMilliseconds: 15000 
#ribbon超时设置
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 5000
